# Generated by Django 4.2.2 on 2023-10-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_users_is_active_users_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
