# Generated by Django 4.2.6 on 2023-10-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_users_bio'),
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressources',
            name='stacks',
            field=models.ManyToManyField(related_name='resource_stacks_associate', to='Account.stacks'),
        ),
    ]
