# Generated by Django 4.2.6 on 2023-10-27 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_role', to='Permission.roles'),
        ),
        migrations.AddField(
            model_name='users',
            name='stacks',
            field=models.ManyToManyField(related_name='users_stacks', to='Account.userstacks'),
        ),
        migrations.AddField(
            model_name='userstacks',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.stacks'),
        ),
        migrations.AddField(
            model_name='userstacks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='members',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='members',
            name='mentore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentore', to=settings.AUTH_USER_MODEL),
        ),
    ]
