# Generated by Django 4.2 on 2023-10-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacks',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
