# Generated by Django 4.2.6 on 2023-10-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_users_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
