# Generated by Django 3.2.11 on 2023-10-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_users_is_active_remove_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Membre'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
